Fix for python path and startup scripts

diff --git a/etc/init.d/metrilyx b/etc/init.d/metrilyx
--- a/etc/init.d/metrilyx
+++ b/etc/init.d/metrilyx
@@ -6,8 +6,14 @@
 
 [ -f "/etc/rc.d/init.d/functions" ] && . /etc/rc.d/init.d/functions
 
+if [ -f "/etc/sysconfig/metrilyx" ]; then
+	. /etc/sysconfig/metrilyx
+else
+	echo "/etc/sysconfig/metrilyx not found!";
+	exit 1;
+fi
+
 NAME="metrilyx"
-APP_HOME="/opt/metrilyx"
 
 NGINX_USER="nginx"
 
@@ -21,7 +27,6 @@ check_paths() {
 }
 
 start() {
-	check_paths;
 	for service in ${SERVICE_START_ORDER}; do
 		service $service start
 	done
@@ -36,6 +41,9 @@ stop() {
 		service $service stop
 	done
 }
+
+### Main ###
+check_paths;
 
 case "$1" in
 	start)
diff --git a/etc/init.d/metrilyx-modelmanager b/etc/init.d/metrilyx-modelmanager
--- a/etc/init.d/metrilyx-modelmanager
+++ b/etc/init.d/metrilyx-modelmanager
@@ -6,6 +6,13 @@
 
 [ -f "/etc/rc.d/init.d/functions" ] && . /etc/rc.d/init.d/functions
 
+if [ -f "/etc/sysconfig/metrilyx" ]; then
+	. /etc/sysconfig/metrilyx
+else
+	echo "/etc/sysconfig/metrilyx not found!";
+	exit 1;
+fi
+
 NAME="metrilyx-modelmanager"
 BIN="/opt/metrilyx/usr/bin/uwsgi"
 APP_HOME="/opt/metrilyx"
@@ -24,7 +31,7 @@ start() {
 	PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
 	if [ "$PIDS" = "" ]; then
 		echo -n "${NAME} starting... "
-		PYTHON_EGG_CACHE=$PYTHON_EGG_CACHE METRILYX_HOME=${APP_HOME} ${BIN} ${DEFAULT_OPTS} > ${LOGFILE} 2>&1 &
+		PYTHONPATH=${PYTHONPATH} PYTHON_EGG_CACHE=$PYTHON_EGG_CACHE METRILYX_HOME=${APP_HOME} ${BIN} ${DEFAULT_OPTS} > ${LOGFILE} 2>&1 &
 		sleep 1;
 		PIDS=`${PGREP} "${BIN} ${DEFAULT_OPTS}" | xargs`;
 		if [ "$PIDS" = "" ]; then
