Fix for startup config

diff --git a/etc/sysconfig/metrilyx b/etc/sysconfig/metrilyx
--- a/etc/sysconfig/metrilyx
+++ b/etc/sysconfig/metrilyx
@@ -13,7 +13,12 @@ if [ -d "${APP_HOME}/usr/local/lib" ]; then
     PYTHONPATH=${APP_HOME}/usr/local/lib/python2.7/dist-packages:${APP_HOME}/usr/local/lib64/python2.7/dist-packages
 fi
 
-UWSGI_BIN=`find ${APP_HOME}/usr -name uwsgi`
+#UWSGI_BIN=`find ${APP_HOME}/usr -name uwsgi`
+UWSGI_BIN=`which uwsgi`
+if [ "$UWSGI_BIN" == "" ]; then
+	echo "uwsgi not found!"
+	exit 1
+fi
 
 NGINX_USER="nginx"
 # Debian http user
